#!/usr/bin/env python3
"""Rebuild the Settings-preview artifacts from their readable sources.

1. Inline src/pkjs/shim/NN-*.js into src/pkjs/clay-custom.js between the
   BEGIN/END GENERATED SHIM markers. Each file loses its /* @noinline */ ...
   /* @endnoinline */ blocks (Node-only require/exports), comments, blank lines
   and indentation, and is prefixed with a /* NN-name.js */ marker.
2. Strip clay-custom.js the same way into src/pkjs/clay-custom.gen.js (CRLF),
   stamped with the SHA-256 of clay-custom.js. test/gen-freshness.test.js
   checks that stamp.

The generated pack block (TREK_GFX_PACK, make_preview_data.py) is left as is.

Usage: python make_shim.py [--check]   (--check: exit 1 if anything is stale)
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PKJS = os.path.join(ROOT, "src", "pkjs")
SHIM_DIR = os.path.join(PKJS, "shim")
SRC = os.path.join(PKJS, "clay-custom.js")
GEN = os.path.join(PKJS, "clay-custom.gen.js")

SHIM_BEGIN = "  /* BEGIN GENERATED SHIM */\n  var TrekShim = (function () {\n"
SHIM_END = ("  return { renderFace: renderFace, VERSION: TREK_SHIM_VERSION,\n"
            "           ATTRIBUTION: PEBBLEOS_ATTRIBUTION };\n"
            "  })();\n  /* END GENERATED SHIM */")
NOINLINE = re.compile(r"/\* @noinline \*/.*?/\* @endnoinline \*/", re.S)
# Characters after which a '/' starts a regex literal rather than a division.
REGEX_PREV = set("(,=:[!&|?{};+-*%<>~^")


def strip_js(src):
    """Drop comments, blank lines and leading indentation; keep strings/regexes."""
    out, i, n, prev = [], 0, len(src), ""
    while i < n:
        c = src[i]
        if c in "\"'`":
            j = i + 1
            while j < n and src[j] != c:
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1])
            i, prev = j + 1, c
            continue
        if src.startswith("//", i):
            j = src.find("\n", i)
            i = n if j < 0 else j
            continue
        if src.startswith("/*", i):
            i = src.find("*/", i + 2) + 2
            continue
        if c == "/" and (prev == "" or prev in REGEX_PREV or prev == "return"):
            j, in_class = i + 1, False
            while j < n:
                if src[j] == "\\":
                    j += 2
                    continue
                if src[j] == "[":
                    in_class = True
                elif src[j] == "]":
                    in_class = False
                elif src[j] == "/" and not in_class:
                    break
                j += 1
            out.append(src[i:j + 1])
            i, prev = j + 1, "/"
            continue
        out.append(c)
        if not c.isspace():
            if not c.isalnum():
                prev = c
            else:
                prev = "return" if "".join(out[-6:]) == "return" else "a"
        i += 1
    lines = (line.strip(" \t").rstrip() for line in "".join(out).split("\n"))
    return [line for line in lines if line]


def build_shim():
    parts = []
    for name in sorted(os.listdir(SHIM_DIR)):
        if not re.match(r"\d\d-.*\.js$", name):
            continue
        with open(os.path.join(SHIM_DIR, name), encoding="utf-8") as f:
            body = NOINLINE.sub("", f.read())
        parts.append("/* %s */" % name)
        parts.extend(strip_js(body))
    return SHIM_BEGIN + "\n".join(parts) + "\n" + SHIM_END


def main():
    check = "--check" in sys.argv[1:]
    with open(SRC, encoding="utf-8") as f:
        src = f.read()
    start = src.index(SHIM_BEGIN)
    end = src.index(SHIM_END) + len(SHIM_END)
    new_src = src[:start] + build_shim() + src[end:]

    sha = hashlib.sha256(new_src.encode("utf-8")).hexdigest()
    header = ["// GENERATED by make_shim.py from clay-custom.js - do not edit.",
              "// Readable source: src/pkjs/clay-custom.js. Regenerate after editing it.",
              "// source-sha256: " + sha]
    new_gen = "\r\n".join(header + strip_js(new_src)).encode("utf-8")
    with open(GEN, "rb") as f:
        old_gen = f.read()

    stale = [p for p, changed in ((SRC, new_src != src), (GEN, new_gen != old_gen)) if changed]
    if check:
        for p in stale:
            print("stale: " + os.path.relpath(p, ROOT))
        return 1 if stale else 0
    with open(SRC, "w", encoding="utf-8", newline="\n") as f:
        f.write(new_src)
    with open(GEN, "wb") as f:
        f.write(new_gen)
    for p in stale:
        print("updated: " + os.path.relpath(p, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
