// GENERATED by gen_frame_tables.py - do not edit by hand.
// Parametric LCARS geometry fitted from the verified-aligned PNG assets,
// plus per-background colour tables and glyph bitmasks. See frame_render.c.
#pragma once
#include <pebble.h>

typedef struct { uint8_t kind; int16_t x, y, w, h; uint8_t p[6]; int8_t o[6]; uint8_t color_idx; } FrameSeg;
// kind: 0 = rounded rect (p = corner radii tl,tr,bl,br)
//       1 = elbow top-left  (p = Rx outer, Ry outer, r inner, tip, arm_v, arm_h)
//       2 = elbow bottom-left (same params)
// o: fractional edge offsets in QUARTER-PIXELS, outward positive:
//    x0,y0,x1,y1 outer edges; nx,ny elbow inner-notch shift (0 for rrect)

#define FRAME_NSEG 13
#define FRAME_NBG  12

#if defined(PBL_PLATFORM_EMERY)
static const FrameSeg FRAME_SEGS[FRAME_NSEG] = {
  { 1,   2,  15,  33,  22, {15,17, 9, 0,14, 8}, { 0, 0,-1, 0, 1, 0}, 0 },
  { 0,  37,  15,  87,   8, { 0, 0, 0, 0, 0, 0}, {-1, 0,-1, 0,-4,-4}, 1 },
  { 0, 126,  15,  68,   8, { 0, 0, 0, 0, 0, 0}, {-1, 0, 1, 0,-4,-4}, 2 },
  { 0,   2,  40,  14,  50, { 0, 0, 0, 0, 0, 0}, { 0, 0, 1, 0,-4,-4}, 3 },
  { 2,   2,  93,  18,  37, {17,19, 8, 0,14,21}, { 0, 0, 1, 1, 1, 2}, 4 },
  { 0,  24, 109,  89,  21, { 0, 0, 0, 0, 0, 0}, { 4, 1,-1, 1,-4,-4}, 5 },
  { 0, 115, 109,  66,  21, { 0, 0, 0, 0, 0, 0}, {-1, 1,-1, 1,-4,-4}, 6 },
  { 0, 183, 109,  17,  21, { 0, 0, 0, 0, 0, 0}, {-1, 1, 0, 1,-4,-4}, 7 },
  { 1,   2, 163,  18,  36, {21,20,11, 0, 6,15}, { 0, 1, 1, 0, 0,-1}, 8 },
  { 0,  24, 163,  69,  15, { 0, 0, 0, 0, 0, 0}, { 4, 1, 0,-1,-4,-4}, 9 },
  { 0,  96, 163, 104,  15, { 0, 0, 0, 1, 0, 0}, { 1, 1, 0,-1,-4,-4}, 10 },
  { 0,   2, 200,   6,  15, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 11 },
  { 0,   2, 216,   6,   6, { 0, 0, 2, 2, 0, 0}, { 0, 0, 0, 1,-4,-4}, 12 },
};
#else  // 144x168 (basalt / aplite / diorite / flint)
static const FrameSeg FRAME_SEGS[FRAME_NSEG] = {
  { 1,   2,  11,  23,  16, {10,10, 4, 0,10, 6}, { 0, 0, 0, 0, 0, 0}, 0 },
  { 0,  27,  11,  62,   6, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 1 },
  { 0,  91,  11,  49,   6, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 2 },
  { 0,   2,  29,  10,  37, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 3 },
  { 2,   2,  68,  13,  28, {15,12, 6, 0,10,16}, { 0, 0, 0, 0, 0, 0}, 4 },
  { 0,  17,  80,  64,  16, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 5 },
  { 0,  83,  80,  47,  16, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 6 },
  { 0, 132,  80,  12,  16, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 7 },
  { 1,   2, 120,  13,  26, {16,13, 6, 0, 4,11}, { 0, 0, 0, 0, 0, 0}, 8 },
  { 0,  17, 120,  50,  11, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 9 },
  { 0,  69, 120,  75,  11, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 10 },
  { 0,   2, 147,   4,  11, { 0, 0, 0, 0, 0, 0}, { 0, 0, 0, 0,-4,-4}, 11 },
  { 0,   2, 159,   4,   4, { 0, 0, 2, 2, 0, 0}, { 0, 0, 0, 0,-4,-4}, 12 },
};
#endif

// Per-background, per-segment colours (GColor8 ARGB8), order = backgroundKeys enum.
static const uint8_t FRAME_COLORS[FRAME_NBG][FRAME_NSEG] = {
  { 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6, 0xD6 }, // default
  { 0xEB, 0xEB, 0xEB, 0xEB, 0xEB, 0xD6, 0xD6, 0xD6, 0xEB, 0xD6, 0xD6, 0xEB, 0xEB }, // BLUEs
  { 0xE7, 0xE7, 0xE7, 0xE7, 0xE7, 0xD2, 0xD2, 0xD2, 0xE7, 0xD2, 0xD2, 0xE7, 0xE7 }, // PURPLEs
  { 0xE9, 0xE9, 0xE9, 0xE9, 0xE9, 0xD4, 0xD4, 0xD4, 0xE9, 0xD4, 0xD4, 0xE9, 0xE9 }, // YELLOWs
  { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }, // white
  { 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xD5, 0xD5, 0xD5, 0xEA, 0xD5, 0xD5, 0xEA, 0xEA }, // grey
  { 0xE0, 0xE0, 0xE0, 0xE0, 0xE0, 0xD0, 0xD0, 0xD0, 0xE0, 0xD0, 0xD0, 0xE0, 0xE0 }, // red
  { 0xFD, 0xFD, 0xFD, 0xE9, 0xE9, 0xE9, 0xE9, 0xE9, 0xEB, 0xEB, 0xEB, 0xEB, 0xEB }, // yellowblue
  { 0xEB, 0xEB, 0xEB, 0xEB, 0xE7, 0xE7, 0xE7, 0xE7, 0xF4, 0xF4, 0xF4, 0xF8, 0xF8 }, // bluepurpleredorange
  { 0xC8, 0xC8, 0xC8, 0xC8, 0xC8, 0xC4, 0xC4, 0xC4, 0xC8, 0xC4, 0xC4, 0xC8, 0xC8 }, // green
  { 0xC3, 0xC3, 0xC3, 0xC3, 0xC3, 0xC2, 0xC2, 0xC2, 0xC3, 0xC2, 0xC2, 0xC3, 0xC3 }, // dkblue
  { 0xED, 0xED, 0xED, 0xCC, 0xC8, 0xC8, 0xC8, 0xC8, 0xF0, 0xF0, 0xF0, 0xF4, 0xF8 }, // borg_bg
};

// Popup pill bars: x,y,w,h, corner radii (tl,tr,bl,br) per piece, panel-local coords.
typedef struct { int16_t x, y, w, h; uint8_t r[4]; } PopupBar;
#if defined(PBL_PLATFORM_EMERY)
static const PopupBar POPUP_BARS_EM[6] = {
  {   0,   0,   9,  12, {6,0,6,0} },
  {  12,   0, 133,  12, {0,0,0,0} },
  { 148,   0,   9,  12, {0,6,0,6} },
  {   0, 110,   9,  12, {6,0,6,0} },
  {  12, 110, 133,  12, {0,0,0,0} },
  { 148, 110,   9,  12, {0,6,0,6} },
};
#define POPUP_BARS POPUP_BARS_EM
#else
static const PopupBar POPUP_BARS_144[6] = {
  {   0,   0,   7,   9, {4,0,4,0} },
  {   9,   0,  95,   9, {0,0,0,0} },
  { 106,   0,   7,   9, {0,4,0,4} },
  {   0,  81,   7,   9, {4,0,4,0} },
  {   9,  81,  95,   9, {0,0,0,0} },
  { 106,  81,   7,   9, {0,4,0,4} },
};
#define POPUP_BARS POPUP_BARS_144
#endif

// Glyph bitmasks (bit x set = ink).
//
// Bluetooth rune: the 144 table is the exact white-ink pixels of the ORIGINAL Trekv5
// IMAGE_BLUETOOTH (14x17 1:1 art, Extracted/<plat>/resources - not the upscaled copies),
// cropped to its 8x15 ink box: two 1px 45-degree polylines plus a staff dotted on the even
// rows. The black pixels of the original are a drop shadow onto the (black) notch and are
// therefore not ink. Time 2 uses its own original art instead: the 11x19 IMAGE_BLUETOOTH
// (bluetooth-bw~emery.png) that 5.x shipped, 2px strokes and a solid staff. A 1px
// redraw of the 144 rune looked too thin at that size.
static const uint32_t GLYPH_RUNE_144_ROWS[15] = { 0x0008, 0x0010, 0x0028, 0x0041, 0x008A, 0x0044, 0x0028, 0x0010, 0x0028, 0x0044, 0x008A, 0x0041, 0x0028, 0x0010, 0x0008 };
#define GLYPH_RUNE_144_W 8
#define GLYPH_RUNE_144_H 15
static const uint32_t GLYPH_RUNE_EM_ROWS[19] = { 0x0020, 0x0060, 0x00E0, 0x01A0, 0x0323, 0x0326, 0x012C, 0x01F8, 0x0070, 0x0070, 0x00F0, 0x01F8, 0x0324, 0x0626, 0x0323, 0x01A0, 0x00E0, 0x0060, 0x0020 };
#define GLYPH_RUNE_EM_W 11
#define GLYPH_RUNE_EM_H 19
static const uint32_t GLYPH_NOBT_EM_ROWS[23] = { 0x0000, 0x0000, 0x0000, 0x0000, 0x8010, 0xC030, 0x6060, 0x30C0, 0x1980, 0x0F00, 0x0600, 0x0E00, 0x1900, 0x1080, 0x2040, 0x4020, 0xC010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 };
#define GLYPH_NOBT_EM_W 20
#define GLYPH_NOBT_EM_H 23
static const uint32_t GLYPH_NOBT_144_ROWS[17] = { 0x0000, 0x0000, 0x0000, 0x0804, 0x0408, 0x0210, 0x0120, 0x00C0, 0x0080, 0x0160, 0x0210, 0x0408, 0x0804, 0x0000, 0x0000, 0x0000, 0x0000 };
#define GLYPH_NOBT_144_W 14
#define GLYPH_NOBT_144_H 17
// Quiet Time indicator: the original Trekv5 IMAGE_ICON_QT (trek-qt.png, 17x16 1:1 art,
// white ink on transparent) at its authored 17x16 frame, so it lands exactly where the
// original's bitmap layer put it. The Time 2 table redraws the same "QT" (2px strokes
// -> 3px, 6px letters -> 9px) rather than up-scaling pixels.
static const uint32_t GLYPH_QT_144_ROWS[16] = { 0x0000, 0x7E78, 0x7EFC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18CC, 0x18FC, 0x1878, 0x00C0, 0x00C0 };
#define GLYPH_QT_144_W 17
#define GLYPH_QT_144_H 16
static const uint32_t GLYPH_QT_EM_ROWS[21] = { 0xFF8FE, 0xFF9FF, 0xFF9FF, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1C7, 0x1C1FF, 0x1C1FF, 0x1C0FE, 0x01C0, 0x01C0, 0x01C0 };
#define GLYPH_QT_EM_W 20
#define GLYPH_QT_EM_H 21
#if defined(PBL_PLATFORM_EMERY)
#define GLYPH_QT_ROWS GLYPH_QT_EM_ROWS
#define GLYPH_QT_W GLYPH_QT_EM_W
#define GLYPH_QT_H GLYPH_QT_EM_H
#else
#define GLYPH_QT_ROWS GLYPH_QT_144_ROWS
#define GLYPH_QT_W GLYPH_QT_144_W
#define GLYPH_QT_H GLYPH_QT_144_H
#endif
#if defined(PBL_PLATFORM_EMERY)
#define GLYPH_RUNE_ROWS GLYPH_RUNE_EM_ROWS
#define GLYPH_RUNE_W GLYPH_RUNE_EM_W
#define GLYPH_RUNE_H GLYPH_RUNE_EM_H
#define GLYPH_NOBT_ROWS GLYPH_NOBT_EM_ROWS
#define GLYPH_NOBT_W GLYPH_NOBT_EM_W
#define GLYPH_NOBT_H GLYPH_NOBT_EM_H
#else
#define GLYPH_RUNE_ROWS GLYPH_RUNE_144_ROWS
#define GLYPH_RUNE_W GLYPH_RUNE_144_W
#define GLYPH_RUNE_H GLYPH_RUNE_144_H
#define GLYPH_NOBT_ROWS GLYPH_NOBT_144_ROWS
#define GLYPH_NOBT_W GLYPH_NOBT_144_W
#define GLYPH_NOBT_H GLYPH_NOBT_144_H
#endif
